# AUTOGENERATED FILE: DO NOT EDIT
# Generated by the AgentRegistry CLI.

ARG DOCKER_REGISTRY=ghcr.io
ARG VERSION=0.7.4
FROM pj3677/kagent-adk:v0.7.11-2-g06db4c30
WORKDIR /app

COPY diceagent/ diceagent/
COPY pyproject.toml pyproject.toml
COPY README.md README.md
COPY .python-version .python-version

RUN uv sync

CMD ["diceagent"]

